### ISSUE TITLE
inventory file

### ISSUE THREAD

**Issue by DeanKamali** [mrlesmithjr/ansible-mongodb#1]
Hi 
can you please add a sample inventory file? I had to spend 1h debugging errors 

Thanks

```
[mongodb_cluster]
mongo1.example.com	ansible_ssh_user=root inventory_hostname=mongodb_replication_master
mongo2.example.com	ansible_ssh_user=root
mongo3.example.com	ansible_ssh_user=root
```

**Comment by mrlesmithjr** [comment]
What sort of errors are you getting? What OS?

Make sure to have DNS functional or update /etc/hosts. You can use the following [ansible-etc-hosts](https://github.com/mrlesmithjr/ansible-etc-hosts) role and use this playbook.

```yaml
---
- hosts: mongodb_cluster
  vars:
    etc_hosts_add_all_hosts: true
    mongodb_config_mongodb: true
    mongodb_bind_ip:
    # - 0.0.0.0
    - 127.0.0.1
    - "{{ ansible_enp0s8['ipv4']['address'] }}"
    mongodb_replication: true
    pri_domain_name: test.vagrant.local
  roles:
    - role: ansible-etc-hosts
    - role: ansible-mongodb
      become: true
  tasks: []
```

For an inventory file the following should work (You do not need to define the `inventory_hostname=mongodb_replication_master`):
```bash
[mongodb_cluster]
mongo1.example.com
mongo2.example.com
mongo3.example.com
```
By default the master is chosen by:
```yaml
# Defines the node which should be considered the replication master
mongodb_replication_master: "{{ groups[mongodb_replication_group][0] }}"
```
The above is in `defaults/main.yml`.
Also, set the following to `true`:
```yaml
# Defines if MongoDB replication is configured
mongodb_replication: false
```

Hope this helps!
